msgid ""
msgstr ""
"Project-Id-Version: qiskitdocs\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-07-16 17:21+0000\n"
"PO-Revision-Date: 2019-09-10 22:42\n"
"Last-Translator: lzdanski\n"
"Language-Team: Portuguese\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.com\n"
"X-Crowdin-Project: qiskitdocs\n"
"X-Crowdin-Language: pt-PT\n"
"X-Crowdin-File: /poRepo/docs/locale/en/LC_MESSAGES/autodoc/qiskit.providers.ibmq.api.exceptions.po\n"
"Language: pt_PT\n"

#: ../../autodoc/qiskit.providers.ibmq.api.exceptions.rst:2
msgid "qiskit.providers.ibmq.api.exceptions module"
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions:1
msgid "Exceptions for IBMQ Connector."
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.ApiError:1
msgid "ベースクラス: :class:`qiskit.providers.ibmq.exceptions.IBMQError`"
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.ApiError:1
msgid "IBMQConnector API error handling base class."
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.BadBackendError:1
#: qiskit.providers.ibmq.api.exceptions.CredentialsError:1
#: qiskit.providers.ibmq.api.exceptions.RegisterSizeError:1
msgid "ベースクラス: :class:`qiskit.providers.ibmq.api.exceptions.ApiError`"
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.BadBackendError:1
msgid "Unavailable backend error."
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.CredentialsError:1
msgid "Exception associated with bad server credentials."
msgstr ""

#: of qiskit.providers.ibmq.api.exceptions.RegisterSizeError:1
msgid "Exception due to exceeding the maximum number of allowed qubits."
msgstr ""

